/** 神明降駕 SOP — 每位神明獨立準備、儀式、請神、起駕特效、回答風格 */
export const GODS = [
  {
    id: 'santaizi',
    name: '三太子',
    title: '中壇元帥',
    image: '/gods/santaizi.webp',
    tagline: '高能量・狼牙棒・七步罡',
    specialties: ['陣頭', '討債', '感情', '出行'],
    replyStyle: '火爆直球、不廢話、愛喊打殺',
    theme: { accent: '#ff2244', glow: 'rgba(255,40,80,.55)', scale: 1.12 },
    possessionClass: 'fx-santaizi',
    fxKind: 'flame-talisman',
    auraColor: '#ff2244',
    entranceLines: ['中壇元帥　降！', '狼牙棒起，陣頭開路！', '哪吒太子在此，誰敢不敬！', '火尖槍出，混天綾飛！'],
    particles: ['#ffd700', '#ff2244', '#ff66cc', '#fff', '#00ffcc'],
    prep: [
      { id: 'betel', label: '檳榔含住', icon: '🥬', type: 'tap' },
      { id: 'gold', label: '金飾佩戴', icon: '📿', type: 'tap' },
      { id: 'voice', label: '嗓門熱身', icon: '📢', type: 'hold', ms: 800, hint: '長按 0.8 秒' },
      { id: 'steps', label: '跳七步', icon: '🦶', type: 'count', need: 7 },
    ],
    ritual: {
      type: 'club',
      mechanic: 'charge',
      label: '狼牙棒・自打',
      icon: '🪵',
      need: 5,
      hint: '長按蓄力，力道環進入<strong>紅區</strong>時放開揮棒。越準越痛，太子越愛。',
      hitLines: ['啪！', '再大力一點！', '太子喜歡這個味', '好，有在痛', '陣頭起了！'],
      perfectLines: ['爆頭！太子上身了！', '這力道夠！', '漂亮，正中天靈蓋！'],
      weakLines: ['太軟了，沒感覺', '搔癢喔？', '重來，太子沒fu'],
      doneLine: '可以請太子了。',
    },
    invoke: {
      label: '請太子',
      hintMobile: '長按並<strong>用力搖晃</strong>，太子喜歡大動作。',
      hintDesktop: '長按並<strong>快速拖曳</strong>模擬跳陣。可用 <kbd>←</kbd><kbd>→</kbd> 加速。',
      holdMs: 1600,
      shakeNeed: 320,
    },
    scanExtra: [
      () => '比對七步罡步……已完成',
      () => `嗓門分貝……${82 + Math.floor(Math.random() * 14)}（太子系門檻）`,
      () => '金飾反光……達標（建議再亮一點）',
    ],
    replyFlavor: 'aggressive',
  },
  {
    id: 'guan',
    name: '關聖帝君',
    title: '武聖',
    image: '/gods/guan.webp',
    tagline: '正氣・參拜・青龍刀勢',
    specialties: ['訴訟', '事業', '正義', '家宅'],
    replyStyle: '威嚴簡短、義字當頭、不許狡辯',
    theme: { accent: '#8b1a1a', glow: 'rgba(180,20,20,.5)', scale: 1.08 },
    possessionClass: 'fx-guan',
    fxKind: 'thunder-blade',
    auraColor: '#c9a227',
    entranceLines: ['關　某　在　此！', '青龍偃月，奸邪退散！', '義之所在，不容含糊！', '赤面長髯，正氣凜然！'],
    particles: ['#c9a227', '#8b0000', '#2d5a27', '#fff', '#88ccff'],
    prep: [
      { id: 'face', label: '正氣凝神', icon: '😤', type: 'hold', ms: 1000, hint: '長按 1 秒' },
      { id: 'blade', label: '青龍刀勢', icon: '⚔️', type: 'count', need: 3 },
      { id: 'robe', label: '整衣佩巾', icon: '👘', type: 'tap' },
    ],
    ritual: {
      type: 'bow',
      mechanic: 'angle',
      label: '參拜三叩',
      icon: '🙏',
      need: 3,
      hint: '緩緩下拉，將身形<strong>鞠躬到位</strong>（進入敬區停住），三叩成禮。太淺、太急皆不算。',
      hitLines: ['一叩首', '再叩首', '三叩首'],
      perfectLines: ['叩得端正，武聖頷首', '禮數周到', '正氣凜然'],
      weakLines: ['拜得太淺，重來', '心不誠，再叩', '腰桿沒下去'],
      doneLine: '禮成。可請關聖。',
    },
    invoke: {
      label: '請關聖',
      hintMobile: '長按「請關聖」，穩穩搖晃，忌浮躁。',
      hintDesktop: '長按並緩慢拖曳。關聖忌急躁。',
      holdMs: 2000,
      shakeNeed: 240,
    },
    scanExtra: [
      () => '比對忠義指數……優',
      () => '青龍刀勢……已完成三遍',
      () => '正氣值……達標',
    ],
    replyFlavor: 'dignified',
  },
  {
    id: 'mazu',
    name: '天上聖母',
    title: '媽祖',
    image: '/gods/mazu.webp',
    tagline: '溫和・敬香・靜心',
    specialties: ['出行', '健康', '家宅', '平安'],
    replyStyle: '慈柔護佑、先安人心、細語叮嚀',
    theme: { accent: '#1a5a8a', glow: 'rgba(60,120,200,.45)', scale: 1.06 },
    possessionClass: 'fx-mazu',
    fxKind: 'sea-wave',
    auraColor: '#4fc3f7',
    entranceLines: ['海　不　揚　波', '天上聖母，慈航普渡。', '風浪暫息，安心前行。', '吾護汝等，平安歸航。'],
    particles: ['#87ceeb', '#ffd700', '#fff', '#c8e6ff', '#4fc3f7'],
    prep: [
      { id: 'incense', label: '敬香三柱', icon: '🪔', type: 'count', need: 3 },
      { id: 'calm', label: '靜心合掌', icon: '🙏', type: 'hold', ms: 1200, hint: '長按 1.2 秒' },
      { id: 'tidy', label: '儀容整理', icon: '✨', type: 'tap' },
    ],
    ritual: {
      type: 'incense',
      mechanic: 'steady',
      label: '點香請駕',
      icon: '🪔',
      need: 3,
      hint: '把香尖移到燭火上，<strong>穩穩停住</strong>直到點燃。手一抖就熄——靜心才點得著。',
      hitLines: ['香火裊裊……', '再點一柱', '心誠則靈'],
      perfectLines: ['一氣呵成，香煙直上', '穩，這柱香夠誠', '裊裊不斷'],
      weakLines: ['抖到熄了', '別急，穩住', '火一晃就滅'],
      doneLine: '香已足。可請媽祖。',
    },
    invoke: {
      label: '請媽祖',
      hintMobile: '長按並<strong>輕輕搖晃</strong>，如乘船。',
      hintDesktop: '長按並輕柔拖曳。媽祖喜溫和。',
      holdMs: 2200,
      shakeNeed: 180,
      gentle: true,
    },
    scanExtra: [
      () => '海風感應……微浪',
      () => '香火濃度……適宜',
      () => '靜心指數……良好',
    ],
    replyFlavor: 'gentle',
  },
  {
    id: 'jigong',
    name: '濟公',
    title: '活佛',
    image: '/gods/jigong.webp',
    tagline: '狂放・拍頭・破規矩',
    specialties: ['感情', '人際', '學業', '投資'],
    replyStyle: '嬉笑怒罵、歪理正說、常叫人喝酒想想',
    theme: { accent: '#b8860b', glow: 'rgba(255,180,40,.5)', scale: 1.1 },
    possessionClass: 'fx-jigong',
    fxKind: 'gold-laughter',
    auraColor: '#ffb028',
    entranceLines: ['哈　哈　哈！', '酒肉穿腸過，活佛在這！', '鞋兒破，帽兒破，濟公來囉！', '別裝正經，說重點啦！'],
    particles: ['#ffd700', '#8b4513', '#ff9900', '#fff', '#ff5722'],
    prep: [
      { id: 'fan', label: '持扇開解', icon: '🪭', type: 'tap' },
      { id: 'wine', label: '酌酒一口', icon: '🍶', type: 'tap' },
      { id: 'laugh', label: '哈哈三聲', icon: '😂', type: 'count', need: 3 },
    ],
    ritual: {
      type: 'slap',
      mechanic: 'rhythm',
      label: '拍頭醒神',
      icon: '👋',
      need: 4,
      hint: '光點掃到<strong>甜蜜區</strong>時拍下去才醒神。亂拍只會「哎唷」，醒神值倒扣。',
      hitLines: ['啪！正好！', '醒一分', '清醒中', '醒了醒了'],
      perfectLines: ['啪！神清氣爽！', '時機剛好，醒透了', '這一巴掌到位'],
      weakLines: ['哎唷！拍歪了', '太早，沒醒', '亂拍會更茫'],
      doneLine: '好了啦，可以請了。',
    },
    invoke: {
      label: '請濟公',
      hintMobile: '長按並<strong>亂搖</strong>就對了。',
      hintDesktop: '長按並瘋狂拖曳。濟公不拘小節。',
      holdMs: 1400,
      shakeNeed: 300,
      chaotic: true,
    },
    scanExtra: [
      () => '酒氣檢測……微量（合格）',
      () => '狂氣指數……偏高但可',
      () => '扇子轉速……夠快',
    ],
    replyFlavor: 'chaotic',
  },
  {
    id: 'wangye',
    name: '五府千歲',
    title: '王爺',
    image: '/gods/wangye.webp',
    landscape: true,
    tagline: '公文・擲筊・陣頭',
    specialties: ['訴訟', '財運', '事業', '討債'],
    replyStyle: '公文體、擲筊定奪、講程序講帳目',
    theme: { accent: '#4a1020', glow: 'rgba(120,0,40,.5)', scale: 1.09 },
    possessionClass: 'fx-wangye',
    fxKind: 'edict-march',
    auraColor: '#cc0033',
    entranceLines: ['王　爺　駕　到！', '公文備齊，筊示開議！', '五府千歲，善惡分明！', '陣頭起，肅靜迴避！'],
    particles: ['#ffd700', '#4a0018', '#880022', '#fff', '#cc0033'],
    prep: [
      { id: 'stamp', label: '印信備齊', icon: '📜', type: 'tap' },
      { id: 'scroll', label: '展開公文', icon: '📋', type: 'tap' },
      { id: 'cymbal', label: '鑼聲三響', icon: '🔔', type: 'count', need: 3 },
    ],
    ritual: {
      type: 'blocks',
      mechanic: 'throw',
      label: '擲筊請示',
      icon: '🥠',
      need: 3,
      hint: '上滑<strong>擲出筊杯</strong>，看天意翻滾落地。擲到三個<strong>聖筊</strong>，王爺方准降駕。',
      hitLines: ['聖筊！准了', '又一聖筊', '天意允准'],
      perfectLines: ['連聖筊！王爺大悅', '筊筊聖筊，氣勢如虹', '一擲定乾坤'],
      weakLines: ['笑筊……王爺在笑', '陰筊，再擲', '蓋杯了，重來'],
      doneLine: '筊示已明。可請王爺。',
    },
    invoke: {
      label: '請王爺',
      hintMobile: '長按並搖晃，如陣頭行進。',
      hintDesktop: '長按並左右拖曳。王爺重陣勢。',
      holdMs: 2000,
      shakeNeed: 260,
    },
    scanExtra: [
      () => '公文格式……廟務通過',
      () => '筊杯配對……正常',
      () => '鑼聲餘韻……尚在',
    ],
    replyFlavor: 'bureaucratic',
  },
];

export function getGod(id) {
  return GODS.find((g) => g.id === id) ?? GODS[0];
}